# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          node-version: '14.x'

      # Install the dependences
      - name: Install
        run: npm install
        
      # Runs all unit tests
      - name: Run tests
        run: npm run test.coverage
        
      # Builds the bundle
      - name: Build
        run: npm run build
        
      # Removes dev dependences
      - name: Removes dev dependences
        run: npm uninstall @types/jest @types/node @typescript-eslint/eslint-plugin @typescript-eslint/parser eslint eslint-config-airbnb-base eslint-plugin-import jest ts-jest typescript
        
      # Archive production artifacts
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: |
            bundle
            node_modules
            package.json
          
      # Archive code coverage results
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage
